from __future__ import annotations


LEGAL_RULES = [
    {
        "id": "RULE_003",
        "name": "缺少合同主体信息",
        "severity": "must_modify",
        "department": "legal",
        "keywords": ["主体", "资格"],
        "logic": {"type": "schema_required", "field": "contract_parties"},
        "suggestion_template": "请补充甲乙双方主体信息。",
    },
    {
        "id": "RULE_004",
        "name": "缺少统一社会信用代码",
        "severity": "suggest_modify",
        "department": "legal",
        "keywords": ["统一社会信用代码", "纳税人识别号"],
        "logic": {"type": "schema_required", "field": "unified_social_credit_code"},
        "suggestion_template": "建议补充统一社会信用代码或纳税人识别号。",
    },
    {
        "id": "RULE_005",
        "name": "缺少授权代表或签章信息",
        "severity": "must_modify",
        "department": "legal",
        "keywords": ["授权代表", "签章"],
        "logic": {"type": "schema_required", "field": "legal_representative"},
        "suggestion_template": "请补充法定代表人、授权代表或签章信息。",
    },
    {
        "id": "RULE_016",
        "name": "缺少违约责任",
        "severity": "must_modify",
        "department": "legal",
        "keywords": ["违约责任", "违约"],
        "logic": {"type": "schema_required", "field": "breach_liability"},
        "suggestion_template": "请补充违约责任条款。",
    },
    {
        "id": "RULE_017",
        "name": "违约责任明显不对等",
        "severity": "suggest_modify",
        "department": "legal",
        "keywords": ["违约责任", "责任明确"],
        "logic": {"type": "breach_equity"},
        "suggestion_template": "建议校核双方违约责任是否明显失衡。",
    },
    {
        "id": "RULE_018",
        "name": "缺少争议解决条款",
        "severity": "must_modify",
        "department": "legal",
        "keywords": ["争议解决"],
        "logic": {"type": "schema_required", "field": "dispute_resolution"},
        "suggestion_template": "请补充争议解决条款。",
    },
    {
        "id": "RULE_019",
        "name": "争议解决地偏向乙方",
        "severity": "suggest_modify",
        "department": "legal",
        "keywords": ["争议解决", "诉讼", "仲裁"],
        "logic": {"type": "dispute_bias"},
        "suggestion_template": "建议调整争议解决地或管辖约定，避免明显偏向对方。",
    },
    {
        "id": "RULE_020",
        "name": "引用废止制度/旧范本",
        "severity": "must_modify",
        "department": "legal",
        "keywords": ["修订", "废止", "替代"],
        "logic": {"type": "reference_outdated"},
        "suggestion_template": "请核对并替换为当前有效制度或范本引用。",
    },
]
